#!/bin/bash


##### IN ROOT

# make a new user 
sudo adduser sghose
visudo # add new user to sudoers


#####

#ok lets get the fastest source
sudo apt-get install netselect-apt
sudo netselect-apt --nonfree --sources `lsb_release -a | grep 'Codename' | awk '{print $2}'`
sudo cat sources.list >> /etc/apt/sources.list
sudo rm sources.list


# yeah i don't know what i didn't just put them in groups using 
#  \ instead of with lots of sudo apt-get's ....
# 

sudo apt-get update
sudo apt-get -y install build-essential libgtk-3-dev \
 libgstreamer0.10-dev libclutter-1.0-dev \
 libwebkitgtk-3.0-dev libgda-5.0-dev \
 clang


sudo apt-get -y install python python3 
sudo apt-get -y install ipython python-scipy python-matplotlib mayavi2 \
  python-sympy cython jython python-networkx python-pexpect python-nose \
  python-setuptools python-sphinx python-pygments python-pip \
  python-twisted python-foolscap python-tk
sudo apt-get -y install ruby1.9.1-full golang

sudo apt-get install wine
dpkg --add-architecture i386
apt-get update
apt-get install wine-bin:i386



sudo apt-get -y install ntop slurm htop \
    git mercurial curl \
  subversion nmap lftp iperf \
  parallel hexedit
echo "alias network='slurm -i venet0'" >> .bashrc
echo " # ntop uses 3000 " >> .bashrc

sudo apt-get -y install xserver-xorg libqt4-dev wine
sudo apt-get -y mplayer deluge deluge-webui deluged deluge-console

git clone git://github.com/joyent/node.git
cd node
./configure
make
sudo make install
cd ..
rm -rf node

#python build bleeding edge versions from source packages

#scikit
git clone git://github.com/scikit-learn/scikit-learn.git
cd scikit-learn
python setup.py build
sudo python setup.py install
cd ..
sudo rm -rf scikit-learn

git clone git://github.com/scikit-image/scikit-image.git
cd scikit-image
python setup.py build
sudo python setup.py install
cd ..
sudo rm -rf scikit-image

# install some node packages

npm install underscore
npm install coffee-script
npm install async
npm install colors

# install bashmarks
git clone git://github.com/huyng/bashmarks.git
cd bashmarks
make install
echo "source ~/.local/bin/bashmarks.sh" >> ~/.bashrc
cd ..
rm -rf bashmarks

##install vim/tmux package managers
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim


# setup diff-so-fancy /w changed default options
npm install -g diff-so-fancy
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
git config --global color.ui true
git config --global color.diff-highlight.oldNormal "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"
git config --global color.diff.meta "227"
git config --global color.diff.frag "magenta bold"
git config --global color.diff.commit "227 bold"
git config --global color.diff.old "red bold"
git config --global color.diff.new "green bold"
git config --global color.diff.whitespace "red reverse"
